### ISSUE TITLE
Running on Android Phone

### ISSUE THREAD

**Issue by SamHam** [hitherejoe/Mondroid#1]
Hi,

I just wanted to find out if this could be run on an Android device? Or is this purely for testing on a desktop?

Many thanks,
Sam

**Comment by hitherejoe** [comment]
This is an Android Application - doesn't run on desktop, just phones :)

**Comment by hitherejoe** [comment]
p.s if you need help getting setup, let me know!

**Comment by SamHam** [comment]
Thanks very much,

That would be greatly appreciated if you could help. Sorry never gone from Github to an app install before.

Sam

**Comment by SamHam** [comment]
I think I have sorted it.

Sorry became obvious to run the 'gadlew' file. Gotten as far as needing the SDK tool android-23, which I believe I just need to download and install in the Anrdoid SDK tonight. Will report back.

Sam

**Comment by SamHam** [comment]
Nailed it.
Cheers buddy,
Sam
